### ISSUE TITLE
Fix section overlap on laptop screens (1200px+)

### ISSUE THREAD

**Issue by ThadIAmir** [ThadIAmir/ThadIAmir.github.io#1]
## Problem
On laptop screens (1200px or larger), the project section overlaps with the skills section, causing a layout issue. This problem does not occur on smaller screens like iPhone or iPod.

## Current Behavior
- Project section collides with the skills section on screens ≥1200px
- Fixed section height of 96vh causes content overflow
- Issue is specific to larger screens

## Root Cause
The issue stems from the following CSS rule:
```css
section {
  padding-top: 4vh;
  height: 96vh;
  margin: 0 10rem;
  box-sizing: border-box;
  min-height: fit-content;
}
```

The fixed height (96vh) doesn't account for varying content lengths, causing overflow and overlap on larger screens.

## Proposed Solution
1. Remove fixed height for sections and use minimum height instead:
```css
section {
  padding-top: 4vh;
  min-height: 96vh; /* Change height to min-height */
  margin: 0 10rem;
  box-sizing: border-box;
}
```

2. Add proper spacing between sections:
```css
section:not(:last-child) {
  margin-bottom: 4rem;
}
```

3. Consider adding a media query for larger screens:
```css
@media screen and (min-width: 1200px) {
  section {
    padding: 6vh 0;
  }
}
```

## Testing Steps
1. Test on screens ≥1200px
2. Verify no overlap between project and skills sections
3. Check that other sections maintain proper spacing
4. Ensure responsive behavior is maintained on smaller screens

## Additional Notes
- This change should maintain the current layout on smaller screens
- Consider testing with various content lengths to ensure flexibility
